"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc: false
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      reactive:
        url: ${DB_URL}
        max-size: 20

"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc: false